#!usr/bin/python
# -*-coding:utf-8-*-

var_1 = 100     # int型
var_2 = 10.0    # float型
var_3 = True    # 布尔型
var_4 = 'abc'   # string型

print var_1     # 100
print var_2     # 10.0
print var_3     # True
print var_4     # abc

# 赋值语句
a = b = c = 1
print a, b, c   # 1 1 1

b, c, d = 1.0, 2, 'Tom'
print b,c,d     # 1.0 2 Tom


# 容器类型：字符串(string)，列表(list)，元组(tuple)，集合(set)，字典(dict)
# 操作有 序列，切片，拼接，部分操作各类型容器均一致，其中列表按隐藏索引修改，元组不可变，集合元素唯一，字典按键取值且键值唯一

# string
mystr_1 = 'bd'
mystr_2 = '8023'
mystr_3 = 'jy'
mystr = 'bd8023jy'

print mystr         # bd8023jy
print mystr[2]      # 8
print mystr[2:]     # 8023jy
print mystr[2:5]    # 802
print mystr[-3:]    # 3jy
print mystr[:-3]    # bd802
print mystr*2       # bd8023jybd8023jy
print mystr_1, mystr_2, mystr_3  # bd 8023 jy
print mystr_1+mystr_2+mystr_3    # bd8023jy

# list
my_list = ['a', 'b', 'c', 'd']
my_list_1 = ['1', '2', '3', '4']

print my_list       # ['a', 'b', 'c', 'd']
print my_list[1]    # b
print my_list[1:3]  # ['b', 'c']
print my_list[-3:]  # ['b', 'c', 'd']
print my_list[:-1]  # ['a', 'b', 'c']
print my_list*2     # ['a', 'b', 'c', 'd', 'a', 'b', 'c', 'd']
print my_list + my_list_1   # ['a', 'b', 'c', 'd', '1', '2', '3', '4']

# tuple
my_tuple = ('a', 'b', 'c', 'd')
my_tuple_1 = ('1', '2', '3', '4')

print my_tuple          # ('a', 'b', 'c', 'd')
print my_tuple[2]       # 取出元素值,c
print my_tuple[1:2]     # 只有一个元素时，末尾分隔符不能少,('b',)
print my_tuple[-1:]     # ('d',)
print my_tuple[:-2]     # ('a', 'b')
print my_tuple*2        # ('a', 'b', 'c', 'd', 'a', 'b', 'c', 'd')
print my_tuple + my_tuple_1 # ('a', 'b', 'c', 'd', '1', '2', '3', '4')

# set
my_set = set(['a', 1, 'b', 2.0, True])
my_set_1 = set(['8023' ,'a', 'b', True])
my_set_2 = set([1, 1, 1, 2, 2, 2, 3, 3, 3])

print my_set_2              # 集合去重,元素唯一，set([1, 2, 3])
print my_set                # 集合不能进行切片和索引操作，set(['a', 1, 2.0, 'b'])
print my_set & my_set_1     # 交集操作，set(['a', True, 'b'])
print my_set | my_set_1     # 并集操作，set(['a', 1, 2.0, 'b', '8023'])
print my_set - my_set_1     # 差集操作，set([2.0])
print my_set_1 - my_set     # 差集操作，set(['8023'])
print my_set ^ my_set_1     # 对称差集，set(['8023', 2.0])

# dictionary
mydict = {}
mydict['one'] = 'This is one'
mydict[2] = 'This is two'

thinydict = {'name': 'Tom', 'age': 10, 'sex': 'male'}

print mydict                        # TypeError: keys() takes no arguments (1 given)
print mydict[2]                     # This is two
print thinydict.keys() is 'name'    # False
print thinydict.keys()              # ['age', 'name', 'sex']
print thinydict.values()            # [10, 'Tom', 'male']
